language: objective-c
rvm: 1.9.3
before_script:
  - brew update
  - brew install xctool
install:
  - gem install cocoapods -v 0.29.0 --no-ri --no-doc
  - pod install
script:
  - xctool ONLY_ACTIVE_ARCH=NO
  - xctool test ONLY_ACTIVE_ARCH=NO
