language: objective-c
before_install:
  - brew update
  - brew install xctool
  - gem install cocoapods -v 0.29.0 --no-ri --no-doc
install:
  - pod install
script:
  - xctool ONLY_ACTIVE_ARCH=NO
  - xctool test ONLY_ACTIVE_ARCH=NO
